### ISSUE TITLE
Question Use Case: Allow List IP - Third Party Service

### ISSUE THREAD

**Issue by fl0wo** [zxkane/snat#898]
## :question: Allow List IP - Third Party Service

Hi, I need to provide a third party a list of allowed IPs from which to filter my requests.

Therefore, my AWS lambdas need to run within those IPs in order to communicate with the third party service.

I am currently solving this problem with a VPC with a NAT Gateway with **_one_** associated EIP. (cannot associate more EIPs to the same NAT)

The problem is that as I scale, I really need **_multiple_** EIPs associated with the NAT, and then to have my Lambda function randomly assigned to one of the static IPs from the list of allowed IPs, every time they got invoked (even the same IP twice is fine, but ideally long-term I want to rotate between all IPs of the subnet).

Do you think snat could be useful for this use case? If yes, how?

Thank you very much for the work done.

### Environment

  - **Version:** latest
  - **CDK CLI Version:** 2.99.0
  - **Node.js Version:** 20
  - **OS:** MacOS

**Comment by zxkane** [comment]
Hi, @fl0wo , this CDK construct only provisions EC2 instances as NAT instances. The EIP will be retained when the instance is terminated or the stack is terminated. However, it won't meet the high availability requirement when the instance fails. At least, you need to take additional steps to re-associate the existing EIP with new NAT instances.

Personally, I think the NAT gateway should meet your requirements. 

1. If the traffic is burst, the NAT gateway could scale out for handling large traffic.
2. If you need more allowed IPs for third-party services, you could provision multiple NAT gateway instances to associate with different EIPs.
